branches:
  only:
  - master
  - release
language: python
python:
- '3.4'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "travisDocs" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
  fi
script:
- python3 tools/sqf_validator.py
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "travisDocs" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    python3 tools/deploy.py;
  fi
env:
  global:
  - secure: 4qbQCb5JPFsjb5vjB+IW6BBXEjJ4kT9GOG/wtLiFRKb8MoK0P4A6hrrRsTX3GQ1xf/Xbk/kkl1Mv0X0pMuGZyEYKwqk3E8lKHysACasQocjKdIPObspvrcaJYMMc/IhZnZt94A91ZUGwTM4LkgTR4QQECPKMMnmIhAqiMRB5mknn7vwc6PwKkReREMCB7oiFlulTYHoQEoKENMBIPVzh6EbfqwCUTP/5VBgkxGIc+5UKGmzdIAzibbyFNgik8HEQWZ8DwFDuTMCS7yqq3lRzIBjU5Q11nNQMivbjCo0kwyjIuBMj3WdNa+pXj7w+tict2R8rU3z1CueBO5mzuF/ehLELkY2HtG5cuZAj3mV+DikQU6GpYfbY6Ko/IsrWm/n0qd1r3RGgLMU7XJCLgia3874mmUdLZuEZmOg6TbAV9dscvbFl8ixBgfzLFZ4WAA++4PQ2R0ggA9NrT0/G5CWkZr2blYaTiRmKtFoyqF/DsiP5TtTBWSP+mttmCvSpoUkpR9GW3OtDxxswG2ppl7s5RRZq3lO6Qsz8h8fqM8YTSsPaE41bggL6laS2URJuINq+zoGB75i3frZ4D0nA8gRxt52pAsVHLyBnfLF4lzh8BrNn0ukDqv93fRtu7AL7WkGjye9l6aZzlDn6STmWMyWINXRcbASC+iTK8NjvfBb2FDM=
notifications:
  email:
    on_success: never
    on_failure: change
